#!/bin/bash

#set -x
export LLVM_HOME=usr/lib/llvm-8
clang++-8 -S -emit-llvm test.cpp
opt-8 -S -instnamer test.ll -o test.ll
mkdir -p _build
pushd _build
cmake ..
make
popd
clang++-8 -S -emit-llvm test.cpp -o test.bc
time opt-8 -instnamer -load _build/*/*BValueContext* -bvc test.bc > /dev/null
#~/llvm-toolchain-8_8~svn353031/build-llvm/bin/opt -debug -instnamer -load _build/*/*SLVA* -slva test.bc > /dev/null
# rm -rf _build test.bc
